import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  PDFDocument,
  rgb,
  StandardFonts,
} from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const LINE_HEIGHT = 26;
const ANSWER_FONT_SIZE = 11;
const CHARS_PER_LINE = 85;
const FOOTER_HEIGHT = 80; // reserved space at bottom of each page

function addPage(pdfDoc: PDFDocument) {
  return pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
}

function drawHeader(
  page: ReturnType<PDFDocument["addPage"]>,
  boldFont: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  submissionId: string,
  submittedDate: string,
  isFirstPage: boolean
) {
  if (isFirstPage) {
    page.drawText("DustOff", {
      x: MARGIN,
      y: PAGE_HEIGHT - 60,
      size: 28,
      font: boldFont,
      color: rgb(0.05, 0.05, 0.05),
    });
    page.drawText("Quiz Results", {
      x: MARGIN,
      y: PAGE_HEIGHT - 90,
      size: 16,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    page.drawLine({
      start: { x: MARGIN, y: PAGE_HEIGHT - 108 },
      end: { x: PAGE_WIDTH - MARGIN, y: PAGE_HEIGHT - 108 },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8),
    });
    page.drawText(`Submission ID: ${submissionId}`, {
      x: MARGIN,
      y: PAGE_HEIGHT - 138,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    page.drawText(`Date: ${submittedDate}`, {
      x: MARGIN,
      y: PAGE_HEIGHT - 156,
      size: 10,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    page.drawText("Your Responses", {
      x: MARGIN,
      y: PAGE_HEIGHT - 195,
      size: 14,
      font: boldFont,
      color: rgb(0.1, 0.1, 0.1),
    });
    return PAGE_HEIGHT - 225; // starting yPos for answers
  } else {
    // Continuation page header
    page.drawText("DustOff — Quiz Results (continued)", {
      x: MARGIN,
      y: PAGE_HEIGHT - 40,
      size: 11,
      font,
      color: rgb(0.5, 0.5, 0.5),
    });
    page.drawLine({
      start: { x: MARGIN, y: PAGE_HEIGHT - 52 },
      end: { x: PAGE_WIDTH - MARGIN, y: PAGE_HEIGHT - 52 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    });
    return PAGE_HEIGHT - 75; // starting yPos for answers on continuation pages
  }
}

function drawFooter(
  page: ReturnType<PDFDocument["addPage"]>,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  pageNumber: number
) {
  page.drawLine({
    start: { x: MARGIN, y: 60 },
    end: { x: PAGE_WIDTH - MARGIN, y: 60 },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.85),
  });
  page.drawText("Generated by DustOff", {
    x: MARGIN,
    y: 42,
    size: 9,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });
  page.drawText(`Page ${pageNumber}`, {
    x: PAGE_WIDTH - MARGIN - 30,
    y: 42,
    size: 9,
    font,
    color: rgb(0.6, 0.6, 0.6),
  });
}

// Wrap a long string into lines of at most maxChars characters
function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + (current ? " " : "") + word).length <= maxChars) {
      current += (current ? " " : "") + word;
    } else {
      if (current) lines.push(current);
      // Hard-break words that are longer than maxChars
      let remaining = word;
      while (remaining.length > maxChars) {
        lines.push(remaining.substring(0, maxChars));
        remaining = remaining.substring(maxChars);
      }
      current = remaining;
    }
  }
  if (current) lines.push(current);
  return lines;
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization") ?? "" },
        },
      }
    );

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const body = await req.json();
    const { answers, userId } = body;

    if (!answers || !Array.isArray(answers)) {
      return new Response(
        JSON.stringify({ error: "Invalid request: answers array is required" }),
        {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 400,
        }
      );
    }

    // Insert quiz submission
    const { data, error } = await supabaseClient
      .from("quiz_submissions")
      .insert({
        user_id: userId ?? null,
        answers,
        submitted_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) {
      console.error("Supabase insert error:", error);
      return new Response(JSON.stringify({ error: error.message }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      });
    }

    // Generate and upload PDF
    let pdfUrl: string | null = null;
    let pdfDebugError: string | null = null; // TODO: remove after debugging
    try {
      const pdfDoc = await PDFDocument.create();
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      const submittedDate = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });

      let pageNumber = 1;
      let currentPage = addPage(pdfDoc);
      let yPos = drawHeader(
        currentPage,
        boldFont,
        font,
        data.id,
        submittedDate,
        true
      );

      for (let i = 0; i < answers.length; i++) {
        const rawText =
          typeof answers[i] === "object"
            ? JSON.stringify(answers[i])
            : String(answers[i]);

        const prefix = `Q${i + 1}: `;
        const wrappedBody = wrapText(rawText, CHARS_PER_LINE - prefix.length);
        const allLines = wrappedBody.map((line, idx) =>
          idx === 0 ? prefix + line : "     " + line
        );

        // Check if this answer block fits; if not, start a new page
        const blockHeight = allLines.length * LINE_HEIGHT + 6; // +6 gap between answers
        if (yPos - blockHeight < FOOTER_HEIGHT) {
          drawFooter(currentPage, font, pageNumber);
          pageNumber++;
          currentPage = addPage(pdfDoc);
          yPos = drawHeader(
            currentPage,
            boldFont,
            font,
            data.id,
            submittedDate,
            false
          );
        }

        for (const line of allLines) {
          currentPage.drawText(line, {
            x: MARGIN,
            y: yPos,
            size: ANSWER_FONT_SIZE,
            font,
            color: rgb(0.2, 0.2, 0.2),
          });
          yPos -= LINE_HEIGHT;
        }
        yPos -= 6; // gap between answers
      }

      drawFooter(currentPage, font, pageNumber);

      const pdfBytes = await pdfDoc.save();
      const fileName = `quiz-results/${data.id}.pdf`;

      const { error: uploadError } = await supabaseAdmin.storage
        .from("quiz-pdfs")
        .upload(fileName, pdfBytes, {
          contentType: "application/pdf",
          upsert: true,
        });

      if (uploadError) {
        console.error("PDF upload error:", uploadError);
        pdfDebugError = `upload: ${uploadError.message}`;
      } else {
        const { data: urlData } = supabaseAdmin.storage
          .from("quiz-pdfs")
          .getPublicUrl(fileName);
        pdfUrl = urlData.publicUrl;

        const { error: updateError } = await supabaseAdmin
          .from("quiz_submissions")
          .update({ pdf_url: pdfUrl })
          .eq("id", data.id);

        if (updateError) {
          console.error("Failed to persist pdf_url:", updateError);
        }
      }
    } catch (pdfErr) {
      const msg = pdfErr instanceof Error ? `${pdfErr.name}: ${pdfErr.message}` : String(pdfErr);
      console.error("PDF generation error:", msg);
      pdfDebugError = `exception: ${msg}`;
    }

    return new Response(
      JSON.stringify({ success: true, lead_id: data.id, pdf_url: pdfUrl, _pdf_error: pdfDebugError }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (err) {
    console.error("Unexpected error:", err);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});
