import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  PDFDocument,
  rgb,
  StandardFonts,
} from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization") ?? "" },
        },
      }
    );

    // Admin client for storage operations (bypasses RLS)
    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const body = await req.json();
    const { answers, userId } = body;

    if (!answers || !Array.isArray(answers)) {
      return new Response(
        JSON.stringify({ error: "Invalid request: answers array is required" }),
        {
          headers: { ...corsHeaders, "Content-Type": "application/json" },
          status: 400,
        }
      );
    }

    // Insert quiz submission
    const { data, error } = await supabaseClient
      .from("quiz_submissions")
      .insert({
        user_id: userId ?? null,
        answers,
        submitted_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) {
      console.error("Supabase insert error:", error);
      return new Response(JSON.stringify({ error: error.message }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      });
    }

    // Generate and upload PDF
    let pdfUrl: string | null = null;
    try {
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([595, 842]); // A4
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
      const { width, height } = page.getSize();

      // Header
      page.drawText("DustOff", {
        x: 50,
        y: height - 60,
        size: 28,
        font: boldFont,
        color: rgb(0.05, 0.05, 0.05),
      });

      page.drawText("Quiz Results", {
        x: 50,
        y: height - 90,
        size: 16,
        font,
        color: rgb(0.4, 0.4, 0.4),
      });

      // Divider
      page.drawLine({
        start: { x: 50, y: height - 108 },
        end: { x: width - 50, y: height - 108 },
        thickness: 1,
        color: rgb(0.8, 0.8, 0.8),
      });

      // Metadata
      const submittedDate = new Date().toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
      page.drawText(`Submission ID: ${data.id}`, {
        x: 50,
        y: height - 138,
        size: 10,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });
      page.drawText(`Date: ${submittedDate}`, {
        x: 50,
        y: height - 156,
        size: 10,
        font,
        color: rgb(0.5, 0.5, 0.5),
      });

      // Answers section
      page.drawText("Your Responses", {
        x: 50,
        y: height - 195,
        size: 14,
        font: boldFont,
        color: rgb(0.1, 0.1, 0.1),
      });

      let yPos = height - 225;
      for (let i = 0; i < answers.length; i++) {
        if (yPos < 80) break; // Prevent overflow off page
        const answerText =
          typeof answers[i] === "object"
            ? JSON.stringify(answers[i])
            : String(answers[i]);
        // Truncate long answers to fit on one line
        const displayText = `Q${i + 1}: ${answerText}`.substring(0, 90);
        page.drawText(displayText, {
          x: 50,
          y: yPos,
          size: 11,
          font,
          color: rgb(0.2, 0.2, 0.2),
        });
        yPos -= 26;
      }

      // Footer
      page.drawLine({
        start: { x: 50, y: 60 },
        end: { x: width - 50, y: 60 },
        thickness: 0.5,
        color: rgb(0.85, 0.85, 0.85),
      });
      page.drawText("Generated by DustOff", {
        x: 50,
        y: 42,
        size: 9,
        font,
        color: rgb(0.6, 0.6, 0.6),
      });

      const pdfBytes = await pdfDoc.save();
      const fileName = `quiz-results/${data.id}.pdf`;

      const { error: uploadError } = await supabaseAdmin.storage
        .from("quiz-pdfs")
        .upload(fileName, pdfBytes, {
          contentType: "application/pdf",
          upsert: true,
        });

      if (uploadError) {
        console.error("PDF upload error:", uploadError);
      } else {
        const { data: urlData } = supabaseAdmin.storage
          .from("quiz-pdfs")
          .getPublicUrl(fileName);
        pdfUrl = urlData.publicUrl;

        // Persist pdf_url back to the submission row
        await supabaseAdmin
          .from("quiz_submissions")
          .update({ pdf_url: pdfUrl })
          .eq("id", data.id);
      }
    } catch (pdfErr) {
      // PDF failure is non-fatal; submission is still saved
      console.error("PDF generation error:", pdfErr);
    }

    return new Response(
      JSON.stringify({ success: true, lead_id: data.id, pdf_url: pdfUrl }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 200,
      }
    );
  } catch (err) {
    console.error("Unexpected error:", err);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      }
    );
  }
});
