import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
import {
  PDFDocument,
  rgb,
  StandardFonts,
} from "https://esm.sh/pdf-lib@1.17.1";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN = 50;
const LINE_HEIGHT = 26;
const ANSWER_FONT_SIZE = 11;
const CHARS_PER_LINE = 85;
const FOOTER_HEIGHT = 80;

const QUESTIONS: Record<number, string> = {
  1: "How mentally clear do you feel right now?",
  2: "How much are you still carrying from earlier today?",
  3: "How much have you been switching between tasks today?",
  4: "How is your body feeling?",
  5: "How many real decisions have you made today?",
  6: "Did you sleep well last night?",
  7: "How much work tension are you likely to carry home?",
  8: "How well has your environment supported your thinking?",
  9: "Does your work feel sustainable?",
};

function addPage(pdfDoc: PDFDocument) {
  return pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
}

function drawHeader(
  page: ReturnType<PDFDocument["addPage"]>,
  boldFont: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  meta: { id: string; date: string; score: number; tier: string; email: string },
  isFirstPage: boolean
) {
  if (isFirstPage) {
    page.drawText("DustOff Reset", {
      x: MARGIN,
      y: PAGE_HEIGHT - 60,
      size: 28,
      font: boldFont,
      color: rgb(0.05, 0.05, 0.05),
    });
    page.drawText("Focus Capacity Profile", {
      x: MARGIN,
      y: PAGE_HEIGHT - 90,
      size: 16,
      font,
      color: rgb(0.4, 0.4, 0.4),
    });
    page.drawLine({
      start: { x: MARGIN, y: PAGE_HEIGHT - 108 },
      end: { x: PAGE_WIDTH - MARGIN, y: PAGE_HEIGHT - 108 },
      thickness: 1,
      color: rgb(0.8, 0.8, 0.8),
    });
    page.drawText(`Email: ${meta.email}`, {
      x: MARGIN, y: PAGE_HEIGHT - 132, size: 10, font, color: rgb(0.5, 0.5, 0.5),
    });
    page.drawText(`Date: ${meta.date}`, {
      x: MARGIN, y: PAGE_HEIGHT - 148, size: 10, font, color: rgb(0.5, 0.5, 0.5),
    });
    page.drawText(`Focus Capacity Score: ${meta.score} / 100  ·  ${meta.tier.toUpperCase()}`, {
      x: MARGIN, y: PAGE_HEIGHT - 164, size: 11, font: boldFont, color: rgb(0.1, 0.1, 0.1),
    });
    page.drawText("Your Responses", {
      x: MARGIN, y: PAGE_HEIGHT - 198, size: 14, font: boldFont, color: rgb(0.1, 0.1, 0.1),
    });
    return PAGE_HEIGHT - 228;
  } else {
    page.drawText("DustOff Reset — Focus Capacity Profile (continued)", {
      x: MARGIN, y: PAGE_HEIGHT - 40, size: 11, font, color: rgb(0.5, 0.5, 0.5),
    });
    page.drawLine({
      start: { x: MARGIN, y: PAGE_HEIGHT - 52 },
      end: { x: PAGE_WIDTH - MARGIN, y: PAGE_HEIGHT - 52 },
      thickness: 0.5,
      color: rgb(0.85, 0.85, 0.85),
    });
    return PAGE_HEIGHT - 75;
  }
}

function drawFooter(
  page: ReturnType<PDFDocument["addPage"]>,
  font: Awaited<ReturnType<PDFDocument["embedFont"]>>,
  pageNumber: number
) {
  page.drawLine({
    start: { x: MARGIN, y: 60 },
    end: { x: PAGE_WIDTH - MARGIN, y: 60 },
    thickness: 0.5,
    color: rgb(0.85, 0.85, 0.85),
  });
  page.drawText("Generated by DustOff Reset · dustoffreset.com", {
    x: MARGIN, y: 42, size: 9, font, color: rgb(0.6, 0.6, 0.6),
  });
  page.drawText(`Page ${pageNumber}`, {
    x: PAGE_WIDTH - MARGIN - 30, y: 42, size: 9, font, color: rgb(0.6, 0.6, 0.6),
  });
}

function wrapText(text: string, maxChars: number): string[] {
  const words = text.split(" ");
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    if ((current + (current ? " " : "") + word).length <= maxChars) {
      current += (current ? " " : "") + word;
    } else {
      if (current) lines.push(current);
      let remaining = word;
      while (remaining.length > maxChars) {
        lines.push(remaining.substring(0, maxChars));
        remaining = remaining.substring(maxChars);
      }
      current = remaining;
    }
  }
  if (current) lines.push(current);
  return lines;
}

// Normalise answers regardless of whether the frontend sends an object
// {1:5, 2:3, ...} or an array [5, 3, ...].
function normaliseAnswers(raw: unknown): Array<{ qNum: number; value: number }> {
  if (Array.isArray(raw)) {
    return raw.map((v, i) => ({ qNum: i + 1, value: Number(v) }));
  }
  if (raw && typeof raw === "object") {
    return Object.entries(raw as Record<string, number>)
      .sort(([a], [b]) => Number(a) - Number(b))
      .map(([k, v]) => ({ qNum: Number(k), value: Number(v) }));
  }
  return [];
}

serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    const supabaseClient = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_ANON_KEY") ?? "",
      {
        global: {
          headers: { Authorization: req.headers.get("Authorization") ?? "" },
        },
      }
    );

    const supabaseAdmin = createClient(
      Deno.env.get("SUPABASE_URL") ?? "",
      Deno.env.get("SUPABASE_SERVICE_ROLE_KEY") ?? ""
    );

    const body = await req.json();
    const { answers: rawAnswers, email, score, utm, userId } = body;

    const answers = normaliseAnswers(rawAnswers);

    if (answers.length === 0) {
      return new Response(
        JSON.stringify({ error: "Invalid request: answers are required" }),
        { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 400 }
      );
    }

    const tier =
      score <= 33 ? "empty_tank" : score <= 66 ? "half_tank" : "full_tank";

    // Insert quiz submission
    const { data, error } = await supabaseClient
      .from("quiz_submissions")
      .insert({
        user_id: userId ?? null,
        email: email ?? null,
        score: score ?? null,
        tier: tier ?? null,
        answers: rawAnswers,
        utm: utm ?? null,
        submitted_at: new Date().toISOString(),
      })
      .select()
      .single();

    if (error) {
      console.error("Supabase insert error:", error);
      return new Response(JSON.stringify({ error: error.message }), {
        headers: { ...corsHeaders, "Content-Type": "application/json" },
        status: 500,
      });
    }

    // Generate and upload PDF
    let pdfUrl: string | null = null;
    let pdfDebugError: string | null = null; // TODO: remove after debugging
    try {
      const pdfDoc = await PDFDocument.create();
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      const submittedDate = new Date().toLocaleDateString("en-US", {
        year: "numeric", month: "long", day: "numeric",
      });

      const tierLabel =
        tier === "full_tank" ? "Green · Stable Capacity"
        : tier === "half_tank" ? "Yellow · Reduced Capacity"
        : "Red · Critical Capacity";

      const meta = {
        id: data.id,
        date: submittedDate,
        score: score ?? 0,
        tier: tierLabel,
        email: email ?? "—",
      };

      let pageNumber = 1;
      let currentPage = addPage(pdfDoc);
      let yPos = drawHeader(currentPage, boldFont, font, meta, true);

      for (const { qNum, value } of answers) {
        const questionText = QUESTIONS[qNum] ?? `Question ${qNum}`;
        const scoreLabel = `${value} / 5`;

        // Question line
        const qLines = wrapText(`Q${qNum}. ${questionText}`, CHARS_PER_LINE);
        const blockHeight = (qLines.length + 1) * LINE_HEIGHT + 10;

        if (yPos - blockHeight < FOOTER_HEIGHT) {
          drawFooter(currentPage, font, pageNumber);
          pageNumber++;
          currentPage = addPage(pdfDoc);
          yPos = drawHeader(currentPage, boldFont, font, meta, false);
        }

        for (const line of qLines) {
          currentPage.drawText(line, {
            x: MARGIN, y: yPos, size: ANSWER_FONT_SIZE,
            font: boldFont, color: rgb(0.15, 0.15, 0.15),
          });
          yPos -= LINE_HEIGHT;
        }
        currentPage.drawText(`Answer: ${scoreLabel}`, {
          x: MARGIN + 12, y: yPos, size: 10,
          font, color: rgb(0.4, 0.4, 0.4),
        });
        yPos -= LINE_HEIGHT + 8;
      }

      drawFooter(currentPage, font, pageNumber);

      const pdfBytes = await pdfDoc.save();
      const fileName = `quiz-results/${data.id}.pdf`;

      const { error: uploadError } = await supabaseAdmin.storage
        .from("quiz-pdfs")
        .upload(fileName, pdfBytes, { contentType: "application/pdf", upsert: true });

      if (uploadError) {
        console.error("PDF upload error:", uploadError);
        pdfDebugError = `upload: ${uploadError.message}`;
      } else {
        const { data: urlData } = supabaseAdmin.storage
          .from("quiz-pdfs")
          .getPublicUrl(fileName);
        pdfUrl = urlData.publicUrl;

        const { error: updateError } = await supabaseAdmin
          .from("quiz_submissions")
          .update({ pdf_url: pdfUrl })
          .eq("id", data.id);

        if (updateError) {
          console.error("Failed to persist pdf_url:", updateError);
        }
      }
    } catch (pdfErr) {
      const msg = pdfErr instanceof Error
        ? `${pdfErr.name}: ${pdfErr.message}`
        : String(pdfErr);
      console.error("PDF generation error:", msg);
      pdfDebugError = `exception: ${msg}`;
    }

    return new Response(
      JSON.stringify({ success: true, lead_id: data.id, pdf_url: pdfUrl, _pdf_error: pdfDebugError }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 200 }
    );
  } catch (err) {
    console.error("Unexpected error:", err);
    return new Response(
      JSON.stringify({ error: "Internal server error" }),
      { headers: { ...corsHeaders, "Content-Type": "application/json" }, status: 500 }
    );
  }
});
